# Generated by Django 6.0.2 on 2026-03-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('doctor', '0001_initial'),
        ('labtechnician', '0001_initial'),
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequestitem',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtechnician.labtest'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.doctorprofile'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacist.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='doctor.prescription'),
        ),
    ]
