# Generated by Django 6.0.2 on 2026-03-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
        ('labtechnician', '0001_initial'),
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labtestrequestitem',
            unique_together={('lab_request', 'lab_test')},
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionitem',
            unique_together={('prescription', 'medicine_name')},
        ),
    ]
