# Generated by Django 6.0.2 on 2026-04-01 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_labtestrequest_results_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequest',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='doctor.consultation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.consultation'),
        ),
    ]
