# Generated by Django 6.0.2 on 2026-03-27 07:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(default='General', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('role', models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Admin', 'Admin')], max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(default='Not Specified', max_length=255)),
                ('salary', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)])),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionistProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='administration.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(default='LIC-000', max_length=50, unique=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to='administration.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnicianProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_details', models.CharField(blank=True, help_text='Optional additional certification', max_length=255, null=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labtech_profile', to='administration.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(default='General', max_length=100)),
                ('consultation_fee', models.PositiveIntegerField(default=500)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='administration.staffprofile')),
            ],
        ),
    ]
