# Generated by Django 6.0.2 on 2026-03-29 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REACTIVATE', 'Reactivate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='license_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['staff_code'], name='administrat_staff_c_93d78c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['role'], name='administrat_role_650e7e_idx'),
        ),
    ]
