# Generated by Django 6.0.2 on 2026-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
