# Generated by Django 6.0.2 on 2026-10-09 19:36

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_pharmacistprofile_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='joining_date',
            field=models.DateField(default=administration.models.current_local_date),
        ),
    ]
