# Generated by Django 6.0.2 on 2026-03-27 07:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('dispense_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispense_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacist.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='DispenseItem',
            fields=[
                ('dispense_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacist.dispense')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist.medicinebatch')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dispense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmacist.dispense')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStockLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('ADD', 'Added'), ('DISPENSE', 'Dispensed'), ('EXPIRED', 'Expired')], max_length=20)),
                ('quantity_changed', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='pharmacist.medicinebatch')),
            ],
        ),
    ]
