# Generated by Django 6.0.2 on 2026-03-29 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_labtestrequestitem_unique_together_and_more'),
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenseitem',
            name='dispense_item_id',
        ),
        migrations.RemoveField(
            model_name='dispenseitem',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='medicinestocklog',
            name='remarks',
        ),
        migrations.AddField(
            model_name='dispenseitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='dispense_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription'),
        ),
        migrations.AlterField(
            model_name='dispenseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicinebill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicinebill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicinestocklog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pharmacist.medicinebatch'),
        ),
        migrations.AlterField(
            model_name='medicinestocklog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
