# Generated by Django 6.0.2 on 2026-03-27 07:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('Out of Service', 'Out of Service')], default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabMaintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('technician_name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='labtechnician.labequipment')),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='doctor.labtestrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('lab_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labtechnician.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labtechnician.laborder')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtest')),
            ],
            options={
                'unique_together': {('lab_order', 'lab_test')},
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_value', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lab_order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labtechnician.laborderitem')),
            ],
        ),
    ]
