# Generated by Django 6.0.2 on 2026-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtechnician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
